import { z } from 'zod'

export const appErrorCodeSchema = z.enum([
  'INVALID_INPUT',
  'UNTRUSTED_SENDER',
  'INTERNAL_ERROR',
  'AUTH_REQUIRED',
  'AUTH_INVALID_CREDENTIALS',
  'AUTH_ACCOUNT_EXISTS',
  'AUTH_INVALID_OTP',
  'AUTH_OTP_EXPIRED',
  'AUTH_OTP_RATE_LIMITED',
  'AUTH_ACCOUNT_NOT_FOUND',
  'FORBIDDEN',
  'USER_NOT_FOUND',
  'ROLE_CONFLICT',
  'SELF_ROLE_CHANGE_FORBIDDEN',
  'LAST_SUPER_ADMIN',
  'REQUEST_ID_CONFLICT',
  'SERVICE_UNAVAILABLE',
  'NOT_FOUND',
  'CONFLICT',
  'CANCELLED',
  'PATH_OUTSIDE_PROJECT',
  'CAPABILITY_SCOPE_DENIED',
  'PERMISSION_DENIED',
  'WORKFLOW_INTEGRITY_FAILED',
  'WORKER_PROTOCOL_INVALID',
  'WORKER_TIMEOUT',
  'CREDENTIAL_UNAVAILABLE',
  'CREDENTIAL_INVALID',
  'MODEL_PROVIDER_ACCESS_DENIED',
  'MODEL_PROVIDER_INVALID_REQUEST',
  'MODEL_PROVIDER_PAYMENT_REQUIRED',
  'MODEL_PROVIDER_RATE_LIMITED',
  'MODEL_PROVIDER_TIMEOUT',
  'MODEL_PROVIDER_UNAVAILABLE',
  'OPENROUTER_REQUEST_FAILED',
  'MODEL_PROVIDER_REQUEST_FAILED',
  'CONTEXT_LIMIT_EXCEEDED',
  'MEDIA_TYPE_UNSUPPORTED',
  'MEDIA_ATTACHMENT_LIMIT_EXCEEDED',
  'MEDIA_SIZE_LIMIT_EXCEEDED',
  'MEDIA_MIME_MISMATCH',
  'MEDIA_IMPORT_FAILED',
  'MEDIA_ASSET_UNAVAILABLE',
  'MEDIA_STORAGE_FULL',
  'MODEL_MODALITY_UNSUPPORTED',
  'MEDIA_GENERATION_FAILED',
  'MEDIA_DOWNLOAD_FAILED',
  'MEDIA_GENERATION_TIMEOUT',
  'PROFILE_AVATAR_UPLOAD_FAILED',
  'NETWORK_PROXY_APPLY_FAILED',
  'CITY_REQUIRED',
  'CITY_NOT_SUPPORTED',
  'WORKFLOW_CHANGED',
  'INVALID_TOOL_SEQUENCE',
  'TOOL_CALL_LIMIT',
  'INVALID_OUTPUT',
  'RESULT_TOO_LARGE',
  'NO_BOUND_PAGE',
  'PAGE_CLOSED',
  'PAGE_BUSY',
  'AUTH_STATE_UNKNOWN',
  'TARGET_AMBIGUOUS',
  'DOMAIN_BLOCKED',
  'MANUAL_ACTION_REQUIRED',
  'MANUAL_INTERVENTION_REQUIRED',
  'PAGE_CHANGED',
  'UNSUPPORTED_CONTROL',
  'ACTION_LIMIT_EXCEEDED',
])

export type AppErrorCode = z.infer<typeof appErrorCodeSchema>

export const appErrorSchema = z.object({
  code: appErrorCodeSchema,
  message: z.string().trim().min(1),
}).strict()

export type AppError = z.infer<typeof appErrorSchema>

const safeErrorMessages: Record<AppErrorCode, string> = {
  INVALID_INPUT: 'The request is invalid.',
  UNTRUSTED_SENDER: 'The request sender is not trusted.',
  INTERNAL_ERROR: 'Unexpected application error',
  AUTH_REQUIRED: 'Authentication is required.',
  AUTH_INVALID_CREDENTIALS: 'The account or password is incorrect.',
  AUTH_ACCOUNT_EXISTS: 'The account already exists.',
  AUTH_INVALID_OTP: 'The verification code is invalid.',
  AUTH_OTP_EXPIRED: 'The verification code has expired.',
  AUTH_OTP_RATE_LIMITED: 'Too many verification code requests. Please try again later.',
  AUTH_ACCOUNT_NOT_FOUND: 'The account was not found.',
  FORBIDDEN: 'You do not have permission to perform this action.',
  USER_NOT_FOUND: 'The user was not found.',
  ROLE_CONFLICT: 'The user role changed. Refresh and try again.',
  SELF_ROLE_CHANGE_FORBIDDEN: 'You cannot change your own role.',
  LAST_SUPER_ADMIN: 'The last super administrator cannot be demoted.',
  REQUEST_ID_CONFLICT: 'The request identifier was already used for a different update.',
  SERVICE_UNAVAILABLE: 'The service is temporarily unavailable.',
  NOT_FOUND: 'The requested resource was not found.',
  CONFLICT: 'The requested operation conflicts with existing state.',
  CANCELLED: 'The operation was cancelled.',
  PATH_OUTSIDE_PROJECT: 'The requested path is outside the project.',
  CAPABILITY_SCOPE_DENIED: 'The requested capability scope is not allowed.',
  PERMISSION_DENIED: 'The requested permission was denied.',
  WORKFLOW_INTEGRITY_FAILED: 'The workflow integrity check failed.',
  WORKER_PROTOCOL_INVALID: 'The worker protocol message is invalid.',
  WORKER_TIMEOUT: 'The worker timed out.',
  CREDENTIAL_UNAVAILABLE: 'The credential is unavailable.',
  CREDENTIAL_INVALID: 'The credential is invalid.',
  MODEL_PROVIDER_ACCESS_DENIED: 'The model provider denied access.',
  MODEL_PROVIDER_INVALID_REQUEST: 'The model provider rejected the request.',
  MODEL_PROVIDER_PAYMENT_REQUIRED: 'The model provider account has insufficient credit.',
  MODEL_PROVIDER_RATE_LIMITED: 'The model provider rate limited the request.',
  MODEL_PROVIDER_TIMEOUT: 'The model provider request timed out.',
  MODEL_PROVIDER_UNAVAILABLE: 'The model provider is unavailable.',
  OPENROUTER_REQUEST_FAILED: 'The OpenRouter request failed.',
  MODEL_PROVIDER_REQUEST_FAILED: 'The model provider request failed.',
  CONTEXT_LIMIT_EXCEEDED: 'The conversation context exceeds the selected model limit.',
  MEDIA_TYPE_UNSUPPORTED: 'This media type is not supported.',
  MEDIA_ATTACHMENT_LIMIT_EXCEEDED: 'The attachment limit was exceeded.',
  MEDIA_SIZE_LIMIT_EXCEEDED: 'The media size limit was exceeded.',
  MEDIA_MIME_MISMATCH: 'The media type does not match its contents.',
  MEDIA_IMPORT_FAILED: 'The media import failed.',
  MEDIA_ASSET_UNAVAILABLE: 'The media asset is unavailable.',
  MEDIA_STORAGE_FULL: 'There is not enough local storage for this media.',
  MODEL_MODALITY_UNSUPPORTED: 'The selected model does not support this media request.',
  MEDIA_GENERATION_FAILED: 'The media generation failed.',
  MEDIA_DOWNLOAD_FAILED: 'The media download failed.',
  MEDIA_GENERATION_TIMEOUT: 'The media generation timed out.',
  PROFILE_AVATAR_UPLOAD_FAILED: 'The profile avatar upload failed.',
  NETWORK_PROXY_APPLY_FAILED: 'The network proxy configuration could not be applied.',
  CITY_REQUIRED: 'Choose a city before running this workflow.',
  CITY_NOT_SUPPORTED: 'This workflow is not available for the selected city.',
  WORKFLOW_CHANGED: 'The workflow changed before it could run. Review and try again.',
  INVALID_TOOL_SEQUENCE: 'The workflow tool sequence is invalid.',
  TOOL_CALL_LIMIT: 'The workflow reached its tool call limit.',
  INVALID_OUTPUT: 'The workflow produced an invalid result.',
  RESULT_TOO_LARGE: 'The workflow result is too large.',
  NO_BOUND_PAGE: 'No browser page is bound to this conversation.',
  PAGE_CLOSED: 'The bound browser page is closed.',
  PAGE_BUSY: 'The bound browser page is busy.',
  AUTH_STATE_UNKNOWN: 'The browser authentication state is unknown.',
  TARGET_AMBIGUOUS: 'The browser target is ambiguous.',
  DOMAIN_BLOCKED: 'This browser action is not allowed for the current domain.',
  MANUAL_ACTION_REQUIRED: 'This browser action requires your confirmation.',
  MANUAL_INTERVENTION_REQUIRED: 'The browser requires your intervention before automation can continue.',
  PAGE_CHANGED: 'The browser page changed. Inspect it again before continuing.',
  UNSUPPORTED_CONTROL: 'This browser control is not supported.',
  ACTION_LIMIT_EXCEEDED: 'The browser operation exceeded a safety boundary.',
}

export function toSafeAppError(error: unknown): AppError {
  if (typeof error === 'object' && error !== null) {
    const parsedCode = appErrorCodeSchema.safeParse((error as { code?: unknown }).code)
    if (parsedCode.success) {
      return { code: parsedCode.data, message: safeErrorMessages[parsedCode.data] }
    }
  }

  return {
    code: 'INTERNAL_ERROR',
    message: safeErrorMessages.INTERNAL_ERROR,
  }
}
